version: '2'

services:
  zookeeper:
    image: saumitras01/zookeeper:v3.4.9
    ports:
      - "2181:2181"
  
  kafka:
    image: saumitras01/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  tweet-producer:
    image: saumitras01/tweet-producer-app:latest
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - kafka
  
  tweet-consumer:
    image: saumitras01/tweet-consumer-app:latest
    ports:
      - "8081:8081"
    tty: true
    depends_on:
      - kafka
